// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace speezs.DataAccess.Models;

public partial class Collectionlook
{
    public int CollectionLookId { get; set; }

    public int? CollectionId { get; set; }

    public int? LookId { get; set; }

    public string Notes { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public DateTime? DateDeleted { get; set; }

    public virtual Favoritecollection Collection { get; set; }

    public virtual Look Look { get; set; }
}