// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace speezs.DataAccess.Models;

public partial class FavoriteCollection
{
    public int CollectionId { get; set; }

    public int? UserId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool? IsPrivate { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public DateTime? DateDeleted { get; set; }

    public virtual ICollection<CollectionLook> Collectionlooks { get; set; } = new List<CollectionLook>();

    public virtual User User { get; set; }
}