// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace speezs.DataAccess.Models;

[Table("images")]
public partial class Image
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("data")]
    public byte[] Data { get; set; }

    [Column("content_type")]
    [StringLength(20)]
    public string ContentType { get; set; }

    [Column("uploaded_at", TypeName = "timestamp without time zone")]
    public DateTime? UploadedAt { get; set; }
}