// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace speezs.DataAccess.Models;

public partial class LookProduct
{
    public int LookProductId { get; set; }

    public int? LookId { get; set; }

    public int? ProductId { get; set; }

    public string ApplicationArea { get; set; }

    public decimal? Intensity { get; set; }

    public int? ApplicationOrder { get; set; }

    public string Notes { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public DateTime? DateDeleted { get; set; }

    public virtual Look Look { get; set; }

    public virtual MakeupProduct Product { get; set; }
}