// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace speezs.DataAccess.Models;

public partial class Look
{
    public int LookId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? CreatedBy { get; set; }

    public bool? IsPublic { get; set; }

    public string Category { get; set; }

    public string ThumbnailUrl { get; set; }

    public decimal? AvgRating { get; set; }

    public int? TotalTransfers { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public DateTime? DateDeleted { get; set; }

    public virtual ICollection<Collectionlook> Collectionlooks { get; set; } = new List<Collectionlook>();

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<Lookproduct> Lookproducts { get; set; } = new List<Lookproduct>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<Transfer> Transfers { get; set; } = new List<Transfer>();
}