// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace speezs.DataAccess.Models;

[Table("lookproducts")]
public partial class Lookproduct
{
    [Key]
    [Column("look_product_id")]
    public int LookProductId { get; set; }

    [Column("look_id")]
    public int? LookId { get; set; }

    [Column("product_id")]
    public int? ProductId { get; set; }

    [Column("is_deleted")]
    public bool? IsDeleted { get; set; }

    [Column("date_created", TypeName = "timestamp without time zone")]
    public DateTime? DateCreated { get; set; }

    [Column("date_modified", TypeName = "timestamp without time zone")]
    public DateTime? DateModified { get; set; }

    [Column("date_deleted", TypeName = "timestamp without time zone")]
    public DateTime? DateDeleted { get; set; }

    [ForeignKey("LookId")]
    [InverseProperty("Lookproducts")]
    public virtual Look Look { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("Lookproducts")]
    public virtual Makeupproduct Product { get; set; }
}