// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace speezs.DataAccess.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public int? LookId { get; set; }

    public int? UserId { get; set; }

    public int? Rating { get; set; }

    public string Comment { get; set; }

    public int? HelpfulVotes { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public DateTime? DateDeleted { get; set; }

    public virtual Look Look { get; set; }

    public virtual User User { get; set; }
}