// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace speezs.DataAccess.Models;

[Table("transactions")]
public partial class Transaction
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("user_id")]
    public int UserId { get; set; }

    [Column("amount")]
    public decimal? Amount { get; set; }

    [Column("description")]
    [StringLength(100)]
    public string Description { get; set; }

    [Column("created_at", TypeName = "timestamp without time zone")]
    public DateTime? CreatedAt { get; set; }

    [Column("completed_at", TypeName = "timestamp without time zone")]
    public DateTime? CompletedAt { get; set; }

    [Column("status")]
    [StringLength(10)]
    public string Status { get; set; }

    [Column("full_name")]
    [StringLength(30)]
    public string FullName { get; set; }

    [Column("country")]
    [StringLength(20)]
    public string Country { get; set; }

    [Column("city")]
    [StringLength(30)]
    public string City { get; set; }

    [Column("zip_code")]
    [StringLength(10)]
    public string ZipCode { get; set; }

    [Column("address")]
    [StringLength(50)]
    public string Address { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Transactions")]
    public virtual User User { get; set; }
}