// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace speezs.DataAccess.Models;

public partial class Userclaim
{
    public int UserId { get; set; }

    public int ClaimId { get; set; }

    public string ClaimType { get; set; }

    public string ClaimValue { get; set; }

    public virtual User User { get; set; }
}