// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace speezs.DataAccess.Models;

public partial class Usersubscription
{
    public int UserSubscriptionId { get; set; }

    public int? UserId { get; set; }

    public int? TierId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public string Status { get; set; }

    public string PaymentMethod { get; set; }

    public bool? AutoRenew { get; set; }

    public DateTime? LastBillingDate { get; set; }

    public DateTime? NextBillingDate { get; set; }

    public DateTime? CancellationDate { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public DateTime? DateDeleted { get; set; }

    public virtual Subscriptiontier Tier { get; set; }

    public virtual User User { get; set; }
}