// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace speezs.DataAccess.Models;

public partial class Userpreference
{
    public int PreferenceId { get; set; }

    public int? UserId { get; set; }

    public string SkinTone { get; set; }

    public string SkinType { get; set; }

    public string FaceShape { get; set; }

    public string EyeColor { get; set; }

    public string PreferredBrands { get; set; }

    public string Allergies { get; set; }

    public int? AiEnhancementLevel { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public DateTime? DateDeleted { get; set; }

    public virtual User User { get; set; }
}