// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace speezs.DataAccess.Models;

public partial class Userresetpasswordcode
{
    public string Email { get; set; }

    public string CodeHash { get; set; }

    public DateTime Expire { get; set; }
}