// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace speezs.DataAccess.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string PasswordSalt { get; set; }

    public string PhoneNumber { get; set; }

    public string FullName { get; set; }

    public string ProfileImageUrl { get; set; }

    public DateTime? LastLogin { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public DateTime? DateDeleted { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? RefreshTokenExpiry { get; set; }

    public virtual ICollection<FavoriteCollection> FavoriteCollections { get; set; } = new List<FavoriteCollection>();

    public virtual ICollection<Look> Looks { get; set; } = new List<Look>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<Transfer> Transfers { get; set; } = new List<Transfer>();

    public virtual UserPreference UserPreference { get; set; }

    public virtual ICollection<UserSubscription> UserSubscriptions { get; set; } = new List<UserSubscription>();
}