// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace speezs.Services.Models.User;

public class CreateUserRequest
{
	public string Email { get; set; }

    public string Password { get; set; }

    public string PhoneNumber { get; set; }

    public string FullName { get; set; }

    public string ProfileImageUrl { get; set; }
}